name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase : ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: cd /home/${{ github.event.repository.name }} && git pull && npm i && pm2 restart ${{ github.event.repository.name }}
